name: Bug Report
description: Report a bug or regression in functionality

body:
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction of the bug/regression with instructions
      placeholder: If the bug/regression does not include a reproduction via StackBlitz or GitHub repo, your issue may be closed without resolution.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: Describe what the expected behavior would be.
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: Versions of Module Federation, Angular, Node, Browser, and operating system
      placeholder: |
        Module Federation:
        Angular:
        Node:
        Browser:
        Operating system(s):
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Other information

  - type: checkboxes
    id: assistance
    attributes:
      label: I would be willing to submit a PR to fix this issue
      description: Assistance is provided if you need help submitting a pull request
      options:
        - label: 'Yes'
        - label: 'No'
